package com.dascom.product.dao;

import com.dascom.product.entity.CpAuthRule;
import com.dascom.product.entity.CpAuthRuleExample;
import java.util.List;
import org.apache.ibatis.annotations.Param;

public interface CpAuthRuleMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table cp_auth_rule
     *
     * @mbggenerated Mon Oct 16 14:54:31 CST 2017
     */
    int countByExample(CpAuthRuleExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table cp_auth_rule
     *
     * @mbggenerated Mon Oct 16 14:54:31 CST 2017
     */
    int deleteByExample(CpAuthRuleExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table cp_auth_rule
     *
     * @mbggenerated Mon Oct 16 14:54:31 CST 2017
     */
    int deleteByPrimaryKey(Integer id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table cp_auth_rule
     *
     * @mbggenerated Mon Oct 16 14:54:31 CST 2017
     */
    int insert(CpAuthRule record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table cp_auth_rule
     *
     * @mbggenerated Mon Oct 16 14:54:31 CST 2017
     */
    int insertSelective(CpAuthRule record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table cp_auth_rule
     *
     * @mbggenerated Mon Oct 16 14:54:31 CST 2017
     */
    List<CpAuthRule> selectByExample(CpAuthRuleExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table cp_auth_rule
     *
     * @mbggenerated Mon Oct 16 14:54:31 CST 2017
     */
    CpAuthRule selectByPrimaryKey(Integer id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table cp_auth_rule
     *
     * @mbggenerated Mon Oct 16 14:54:31 CST 2017
     */
    int updateByExampleSelective(@Param("record") CpAuthRule record, @Param("example") CpAuthRuleExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table cp_auth_rule
     *
     * @mbggenerated Mon Oct 16 14:54:31 CST 2017
     */
    int updateByExample(@Param("record") CpAuthRule record, @Param("example") CpAuthRuleExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table cp_auth_rule
     *
     * @mbggenerated Mon Oct 16 14:54:31 CST 2017
     */
    int updateByPrimaryKeySelective(CpAuthRule record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table cp_auth_rule
     *
     * @mbggenerated Mon Oct 16 14:54:31 CST 2017
     */
    int updateByPrimaryKey(CpAuthRule record);
}