package com.dascom.product.dao;

import com.dascom.product.entity.CpAuthGroup;
import com.dascom.product.entity.CpAuthGroupExample;
import java.util.List;
import org.apache.ibatis.annotations.Param;

public interface CpAuthGroupMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table cp_auth_group
     *
     * @mbggenerated Mon Oct 16 14:54:31 CST 2017
     */
    int countByExample(CpAuthGroupExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table cp_auth_group
     *
     * @mbggenerated Mon Oct 16 14:54:31 CST 2017
     */
    int deleteByExample(CpAuthGroupExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table cp_auth_group
     *
     * @mbggenerated Mon Oct 16 14:54:31 CST 2017
     */
    int deleteByPrimaryKey(Integer id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table cp_auth_group
     *
     * @mbggenerated Mon Oct 16 14:54:31 CST 2017
     */
    int insert(CpAuthGroup record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table cp_auth_group
     *
     * @mbggenerated Mon Oct 16 14:54:31 CST 2017
     */
    int insertSelective(CpAuthGroup record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table cp_auth_group
     *
     * @mbggenerated Mon Oct 16 14:54:31 CST 2017
     */
    List<CpAuthGroup> selectByExample(CpAuthGroupExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table cp_auth_group
     *
     * @mbggenerated Mon Oct 16 14:54:31 CST 2017
     */
    CpAuthGroup selectByPrimaryKey(Integer id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table cp_auth_group
     *
     * @mbggenerated Mon Oct 16 14:54:31 CST 2017
     */
    int updateByExampleSelective(@Param("record") CpAuthGroup record, @Param("example") CpAuthGroupExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table cp_auth_group
     *
     * @mbggenerated Mon Oct 16 14:54:31 CST 2017
     */
    int updateByExample(@Param("record") CpAuthGroup record, @Param("example") CpAuthGroupExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table cp_auth_group
     *
     * @mbggenerated Mon Oct 16 14:54:31 CST 2017
     */
    int updateByPrimaryKeySelective(CpAuthGroup record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table cp_auth_group
     *
     * @mbggenerated Mon Oct 16 14:54:31 CST 2017
     */
    int updateByPrimaryKey(CpAuthGroup record);
}