package com.dascom.product.dao;

import com.dascom.product.entity.CpAuthGroupAccess;
import com.dascom.product.entity.CpAuthGroupAccessExample;
import java.util.List;
import org.apache.ibatis.annotations.Param;

public interface CpAuthGroupAccessMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table cp_auth_group_access
     *
     * @mbggenerated Mon Oct 16 14:54:31 CST 2017
     */
    int countByExample(CpAuthGroupAccessExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table cp_auth_group_access
     *
     * @mbggenerated Mon Oct 16 14:54:31 CST 2017
     */
    int deleteByExample(CpAuthGroupAccessExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table cp_auth_group_access
     *
     * @mbggenerated Mon Oct 16 14:54:31 CST 2017
     */
    int insert(CpAuthGroupAccess record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table cp_auth_group_access
     *
     * @mbggenerated Mon Oct 16 14:54:31 CST 2017
     */
    int insertSelective(CpAuthGroupAccess record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table cp_auth_group_access
     *
     * @mbggenerated Mon Oct 16 14:54:31 CST 2017
     */
    List<CpAuthGroupAccess> selectByExample(CpAuthGroupAccessExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table cp_auth_group_access
     *
     * @mbggenerated Mon Oct 16 14:54:31 CST 2017
     */
    int updateByExampleSelective(@Param("record") CpAuthGroupAccess record, @Param("example") CpAuthGroupAccessExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table cp_auth_group_access
     *
     * @mbggenerated Mon Oct 16 14:54:31 CST 2017
     */
    int updateByExample(@Param("record") CpAuthGroupAccess record, @Param("example") CpAuthGroupAccessExample example);
}