package com.dascom.product.dao;

import com.dascom.product.entity.CpGoodsType;
import com.dascom.product.entity.CpGoodsTypeExample;
import java.util.List;
import org.apache.ibatis.annotations.Param;

public interface CpGoodsTypeMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table cp_goods_type
     *
     * @mbggenerated Mon Oct 16 14:54:31 CST 2017
     */
    int countByExample(CpGoodsTypeExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table cp_goods_type
     *
     * @mbggenerated Mon Oct 16 14:54:31 CST 2017
     */
    int deleteByExample(CpGoodsTypeExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table cp_goods_type
     *
     * @mbggenerated Mon Oct 16 14:54:31 CST 2017
     */
    int deleteByPrimaryKey(Integer id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table cp_goods_type
     *
     * @mbggenerated Mon Oct 16 14:54:31 CST 2017
     */
    int insert(CpGoodsType record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table cp_goods_type
     *
     * @mbggenerated Mon Oct 16 14:54:31 CST 2017
     */
    int insertSelective(CpGoodsType record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table cp_goods_type
     *
     * @mbggenerated Mon Oct 16 14:54:31 CST 2017
     */
    List<CpGoodsType> selectByExample(CpGoodsTypeExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table cp_goods_type
     *
     * @mbggenerated Mon Oct 16 14:54:31 CST 2017
     */
    CpGoodsType selectByPrimaryKey(Integer id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table cp_goods_type
     *
     * @mbggenerated Mon Oct 16 14:54:31 CST 2017
     */
    int updateByExampleSelective(@Param("record") CpGoodsType record, @Param("example") CpGoodsTypeExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table cp_goods_type
     *
     * @mbggenerated Mon Oct 16 14:54:31 CST 2017
     */
    int updateByExample(@Param("record") CpGoodsType record, @Param("example") CpGoodsTypeExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table cp_goods_type
     *
     * @mbggenerated Mon Oct 16 14:54:31 CST 2017
     */
    int updateByPrimaryKeySelective(CpGoodsType record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table cp_goods_type
     *
     * @mbggenerated Mon Oct 16 14:54:31 CST 2017
     */
    int updateByPrimaryKey(CpGoodsType record);
}