package com.dascom.product.dao;

import com.dascom.product.entity.CpGoods;
import com.dascom.product.entity.CpGoodsExample;
import java.util.List;
import org.apache.ibatis.annotations.Param;

public interface CpGoodsMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table cp_goods
     *
     * @mbggenerated Mon Oct 16 14:54:31 CST 2017
     */
    int countByExample(CpGoodsExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table cp_goods
     *
     * @mbggenerated Mon Oct 16 14:54:31 CST 2017
     */
    int deleteByExample(CpGoodsExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table cp_goods
     *
     * @mbggenerated Mon Oct 16 14:54:31 CST 2017
     */
    int deleteByPrimaryKey(Integer id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table cp_goods
     *
     * @mbggenerated Mon Oct 16 14:54:31 CST 2017
     */
    int insert(CpGoods record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table cp_goods
     *
     * @mbggenerated Mon Oct 16 14:54:31 CST 2017
     */
    int insertSelective(CpGoods record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table cp_goods
     *
     * @mbggenerated Mon Oct 16 14:54:31 CST 2017
     */
    List<CpGoods> selectByExampleWithBLOBs(CpGoodsExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table cp_goods
     *
     * @mbggenerated Mon Oct 16 14:54:31 CST 2017
     */
    List<CpGoods> selectByExample(CpGoodsExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table cp_goods
     *
     * @mbggenerated Mon Oct 16 14:54:31 CST 2017
     */
    CpGoods selectByPrimaryKey(Integer id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table cp_goods
     *
     * @mbggenerated Mon Oct 16 14:54:31 CST 2017
     */
    int updateByExampleSelective(@Param("record") CpGoods record, @Param("example") CpGoodsExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table cp_goods
     *
     * @mbggenerated Mon Oct 16 14:54:31 CST 2017
     */
    int updateByExampleWithBLOBs(@Param("record") CpGoods record, @Param("example") CpGoodsExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table cp_goods
     *
     * @mbggenerated Mon Oct 16 14:54:31 CST 2017
     */
    int updateByExample(@Param("record") CpGoods record, @Param("example") CpGoodsExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table cp_goods
     *
     * @mbggenerated Mon Oct 16 14:54:31 CST 2017
     */
    int updateByPrimaryKeySelective(CpGoods record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table cp_goods
     *
     * @mbggenerated Mon Oct 16 14:54:31 CST 2017
     */
    int updateByPrimaryKeyWithBLOBs(CpGoods record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table cp_goods
     *
     * @mbggenerated Mon Oct 16 14:54:31 CST 2017
     */
    int updateByPrimaryKey(CpGoods record);
}