package com.dascom.product.dao;

import com.dascom.product.entity.CpResource;
import com.dascom.product.entity.CpResourceExample;
import com.dascom.product.entity.CpResourceWithBLOBs;
import java.util.List;
import org.apache.ibatis.annotations.Param;

public interface CpResourceMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table cp_resource
     *
     * @mbggenerated Mon Oct 16 14:54:31 CST 2017
     */
    int countByExample(CpResourceExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table cp_resource
     *
     * @mbggenerated Mon Oct 16 14:54:31 CST 2017
     */
    int deleteByExample(CpResourceExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table cp_resource
     *
     * @mbggenerated Mon Oct 16 14:54:31 CST 2017
     */
    int deleteByPrimaryKey(Integer id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table cp_resource
     *
     * @mbggenerated Mon Oct 16 14:54:31 CST 2017
     */
    int insert(CpResourceWithBLOBs record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table cp_resource
     *
     * @mbggenerated Mon Oct 16 14:54:31 CST 2017
     */
    int insertSelective(CpResourceWithBLOBs record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table cp_resource
     *
     * @mbggenerated Mon Oct 16 14:54:31 CST 2017
     */
    List<CpResourceWithBLOBs> selectByExampleWithBLOBs(CpResourceExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table cp_resource
     *
     * @mbggenerated Mon Oct 16 14:54:31 CST 2017
     */
    List<CpResource> selectByExample(CpResourceExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table cp_resource
     *
     * @mbggenerated Mon Oct 16 14:54:31 CST 2017
     */
    CpResourceWithBLOBs selectByPrimaryKey(Integer id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table cp_resource
     *
     * @mbggenerated Mon Oct 16 14:54:31 CST 2017
     */
    int updateByExampleSelective(@Param("record") CpResourceWithBLOBs record, @Param("example") CpResourceExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table cp_resource
     *
     * @mbggenerated Mon Oct 16 14:54:31 CST 2017
     */
    int updateByExampleWithBLOBs(@Param("record") CpResourceWithBLOBs record, @Param("example") CpResourceExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table cp_resource
     *
     * @mbggenerated Mon Oct 16 14:54:31 CST 2017
     */
    int updateByExample(@Param("record") CpResource record, @Param("example") CpResourceExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table cp_resource
     *
     * @mbggenerated Mon Oct 16 14:54:31 CST 2017
     */
    int updateByPrimaryKeySelective(CpResourceWithBLOBs record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table cp_resource
     *
     * @mbggenerated Mon Oct 16 14:54:31 CST 2017
     */
    int updateByPrimaryKeyWithBLOBs(CpResourceWithBLOBs record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table cp_resource
     *
     * @mbggenerated Mon Oct 16 14:54:31 CST 2017
     */
    int updateByPrimaryKey(CpResource record);
}