package com.dascom.product.dao;

import com.dascom.product.entity.CpResourceSet;
import com.dascom.product.entity.CpResourceSetExample;
import java.util.List;
import org.apache.ibatis.annotations.Param;

public interface CpResourceSetMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table cp_resource_set
     *
     * @mbggenerated Mon Oct 16 14:54:31 CST 2017
     */
    int countByExample(CpResourceSetExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table cp_resource_set
     *
     * @mbggenerated Mon Oct 16 14:54:31 CST 2017
     */
    int deleteByExample(CpResourceSetExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table cp_resource_set
     *
     * @mbggenerated Mon Oct 16 14:54:31 CST 2017
     */
    int deleteByPrimaryKey(Integer id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table cp_resource_set
     *
     * @mbggenerated Mon Oct 16 14:54:31 CST 2017
     */
    int insert(CpResourceSet record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table cp_resource_set
     *
     * @mbggenerated Mon Oct 16 14:54:31 CST 2017
     */
    int insertSelective(CpResourceSet record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table cp_resource_set
     *
     * @mbggenerated Mon Oct 16 14:54:31 CST 2017
     */
    List<CpResourceSet> selectByExample(CpResourceSetExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table cp_resource_set
     *
     * @mbggenerated Mon Oct 16 14:54:31 CST 2017
     */
    CpResourceSet selectByPrimaryKey(Integer id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table cp_resource_set
     *
     * @mbggenerated Mon Oct 16 14:54:31 CST 2017
     */
    int updateByExampleSelective(@Param("record") CpResourceSet record, @Param("example") CpResourceSetExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table cp_resource_set
     *
     * @mbggenerated Mon Oct 16 14:54:31 CST 2017
     */
    int updateByExample(@Param("record") CpResourceSet record, @Param("example") CpResourceSetExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table cp_resource_set
     *
     * @mbggenerated Mon Oct 16 14:54:31 CST 2017
     */
    int updateByPrimaryKeySelective(CpResourceSet record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table cp_resource_set
     *
     * @mbggenerated Mon Oct 16 14:54:31 CST 2017
     */
    int updateByPrimaryKey(CpResourceSet record);
}