package com.dascom.product.dao;

import com.dascom.product.entity.CpResource;
import com.dascom.product.entity.CpResourceExample;
import com.dascom.product.entity.CpResourceWithBLOBs;

import java.util.List;

import org.apache.ibatis.annotations.Param;

public interface CpResourceMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table cp_resource
     *
     * @mbggenerated Mon Oct 16 14:54:31 CST 2017
     */
    int countByExample(CpResourceExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table cp_resource
     *
     * @mbggenerated Mon Oct 16 14:54:31 CST 2017
     */
    int deleteByExample(CpResourceExample example);

    int deleteByPrimaryKey(Integer id);

    int insert(CpResourceWithBLOBs record);

    int insertSelective(CpResource record);

    List<CpResourceWithBLOBs> selectByExampleWithBLOBs(CpResourceExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table cp_resource
     *
     * @mbggenerated Mon Oct 16 14:54:31 CST 2017
     */
    List<CpResource> selectByExample(CpResourceExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table cp_resource
     *
     * @mbggenerated Mon Oct 16 14:54:31 CST 2017
     */
    CpResourceWithBLOBs selectByPrimaryKey(Integer id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table cp_resource
     *
     * @mbggenerated Mon Oct 16 14:54:31 CST 2017
     */
    int updateByExampleSelective(@Param("record") CpResourceWithBLOBs record, @Param("example") CpResourceExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table cp_resource
     *
     * @mbggenerated Mon Oct 16 14:54:31 CST 2017
     */
    int updateByExampleWithBLOBs(@Param("record") CpResourceWithBLOBs record, @Param("example") CpResourceExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table cp_resource
     *
     * @mbggenerated Mon Oct 16 14:54:31 CST 2017
     */
    int updateByExample(@Param("record") CpResource record, @Param("example") CpResourceExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table cp_resource
     *
     * @mbggenerated Mon Oct 16 14:54:31 CST 2017
     */
    int updateByPrimaryKeySelective(CpResource res);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table cp_resource
     *
     * @mbggenerated Mon Oct 16 14:54:31 CST 2017
     */
    int updateByPrimaryKeyWithBLOBs(CpResourceWithBLOBs record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table cp_resource
     *
     * @mbggenerated Mon Oct 16 14:54:31 CST 2017
     */
    int updateByPrimaryKey(CpResource record);
    
    /**
     * 查看应用软件
     * @param string
     * @param like 
     * @return
     */
	List<CpResourceExample> selectByTypeTitle(@Param("title")String title, @Param("like")String like);
}