package com.dascom.product.dao;

import com.dascom.product.entity.CpSoftware;
import com.dascom.product.entity.CpSoftwareExample;
import java.util.List;
import org.apache.ibatis.annotations.Param;

public interface CpSoftwareMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table cp_software
     *
     * @mbggenerated Mon Oct 16 14:54:31 CST 2017
     */
    int countByExample(CpSoftwareExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table cp_software
     *
     * @mbggenerated Mon Oct 16 14:54:31 CST 2017
     */
    int deleteByExample(CpSoftwareExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table cp_software
     *
     * @mbggenerated Mon Oct 16 14:54:31 CST 2017
     */
    int deleteByPrimaryKey(Integer id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table cp_software
     *
     * @mbggenerated Mon Oct 16 14:54:31 CST 2017
     */
    int insert(CpSoftware record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table cp_software
     *
     * @mbggenerated Mon Oct 16 14:54:31 CST 2017
     */
    int insertSelective(CpSoftware record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table cp_software
     *
     * @mbggenerated Mon Oct 16 14:54:31 CST 2017
     */
    List<CpSoftware> selectByExampleWithBLOBs(CpSoftwareExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table cp_software
     *
     * @mbggenerated Mon Oct 16 14:54:31 CST 2017
     */
    List<CpSoftware> selectByExample(CpSoftwareExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table cp_software
     *
     * @mbggenerated Mon Oct 16 14:54:31 CST 2017
     */
    CpSoftware selectByPrimaryKey(Integer id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table cp_software
     *
     * @mbggenerated Mon Oct 16 14:54:31 CST 2017
     */
    int updateByExampleSelective(@Param("record") CpSoftware record, @Param("example") CpSoftwareExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table cp_software
     *
     * @mbggenerated Mon Oct 16 14:54:31 CST 2017
     */
    int updateByExampleWithBLOBs(@Param("record") CpSoftware record, @Param("example") CpSoftwareExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table cp_software
     *
     * @mbggenerated Mon Oct 16 14:54:31 CST 2017
     */
    int updateByExample(@Param("record") CpSoftware record, @Param("example") CpSoftwareExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table cp_software
     *
     * @mbggenerated Mon Oct 16 14:54:31 CST 2017
     */
    int updateByPrimaryKeySelective(CpSoftware record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table cp_software
     *
     * @mbggenerated Mon Oct 16 14:54:31 CST 2017
     */
    int updateByPrimaryKeyWithBLOBs(CpSoftware record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table cp_software
     *
     * @mbggenerated Mon Oct 16 14:54:31 CST 2017
     */
    int updateByPrimaryKey(CpSoftware record);
}