package com.dascom.product.dao;

import com.dascom.product.entity.CpUser;
import com.dascom.product.entity.CpUserExample;

import java.util.List;

import org.apache.ibatis.annotations.Param;

public interface CpUserMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table cp_user
     *
     * @mbggenerated Mon Oct 16 14:54:31 CST 2017
     */
    int countByExample(CpUserExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table cp_user
     *
     * @mbggenerated Mon Oct 16 14:54:31 CST 2017
     */
    int deleteByExample(CpUserExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table cp_user
     *
     * @mbggenerated Mon Oct 16 14:54:31 CST 2017
     */
    int deleteByPrimaryKey(Integer id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table cp_user
     *
     * @mbggenerated Mon Oct 16 14:54:31 CST 2017
     */
    int insert(CpUser record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table cp_user
     *
     * @mbggenerated Mon Oct 16 14:54:31 CST 2017
     */
    int insertSelective(CpUser record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table cp_user
     *
     * @mbggenerated Mon Oct 16 14:54:31 CST 2017
     */
    List<CpUser> selectByExample(CpUserExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table cp_user
     *
     * @mbggenerated Mon Oct 16 14:54:31 CST 2017
     */
    CpUser selectByPrimaryKey(Integer id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table cp_user
     *
     * @mbggenerated Mon Oct 16 14:54:31 CST 2017
     */
    int updateByExampleSelective(@Param("record") CpUser record, @Param("example") CpUserExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table cp_user
     *
     * @mbggenerated Mon Oct 16 14:54:31 CST 2017
     */
    int updateByExample(@Param("record") CpUser record, @Param("example") CpUserExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table cp_user
     *
     * @mbggenerated Mon Oct 16 14:54:31 CST 2017
     */
    int updateByPrimaryKeySelective(CpUser record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table cp_user
     *
     * @mbggenerated Mon Oct 16 14:54:31 CST 2017
     */
    int updateByPrimaryKey(CpUser record);

	//========================================================
    /**
     * 查询用户
     * @param username
     * @return
     */
	CpUser selectCpUserByUsername(String username);
}